config/routes.rb
Rails.application.routes.draw do
  resources :destinations

  resources :destination_types

  resources :users

end

app/models/destination.rb
class Destination < ActiveRecord::Base
  belongs_to :destination_type
end

app/models/destination_type.rb
class DestinationType < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/destination_types_controller.rb
class DestinationTypesController < ApplicationController
  before_action :set_destination_type, only: [:show, :edit, :update, :destroy]

  # GET /destination_types
  # GET /destination_types.json
  def index
    @destination_types = DestinationType.all
  end

  # GET /destination_types/1
  # GET /destination_types/1.json
  def show
  end

  # GET /destination_types/new
  def new
    @destination_type = DestinationType.new
  end

  # GET /destination_types/1/edit
  def edit
  end

  # POST /destination_types
  # POST /destination_types.json
  def create
    @destination_type = DestinationType.new(destination_type_params)

    respond_to do |format|
      if @destination_type.save
        format.html { redirect_to @destination_type, notice: 'Destination type was successfully created.' }
        format.json { render :show, status: :created, location: @destination_type }
      else
        format.html { render :new }
        format.json { render json: @destination_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /destination_types/1
  # PATCH/PUT /destination_types/1.json
  def update
    respond_to do |format|
      if @destination_type.update(destination_type_params)
        format.html { redirect_to @destination_type, notice: 'Destination type was successfully updated.' }
        format.json { render :show, status: :ok, location: @destination_type }
      else
        format.html { render :edit }
        format.json { render json: @destination_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /destination_types/1
  # DELETE /destination_types/1.json
  def destroy
    @destination_type.destroy
    respond_to do |format|
      format.html { redirect_to destination_types_url, notice: 'Destination type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_destination_type
      @destination_type = DestinationType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def destination_type_params
      params.require(:destination_type).permit(:name)
    end
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :set_destination, only: [:show, :edit, :update, :destroy]

  # GET /destinations
  # GET /destinations.json
  def index
    @destinations = Destination.all
  end

  # GET /destinations/1
  # GET /destinations/1.json
  def show
  end

  # GET /destinations/new
  def new
    @destination = Destination.new
    @destination_types = DestinationType.all.collect{|e|[e.name, e.id]}
  end

  # GET /destinations/1/edit
  def edit
    @destination_types = DestinationType.all.collect{|e|[e.name, e.id]}
  end

  # POST /destinations
  # POST /destinations.json
  def create
    @destination = Destination.new(destination_params)

    respond_to do |format|
      if @destination.save
        format.html { redirect_to @destination, notice: 'Destination was successfully created.' }
        format.json { render :show, status: :created, location: @destination }
      else
        format.html { render :new }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /destinations/1
  # PATCH/PUT /destinations/1.json
  def update
    respond_to do |format|
      if @destination.update(destination_params)
        format.html { redirect_to @destination, notice: 'Destination was successfully updated.' }
        format.json { render :show, status: :ok, location: @destination }
      else
        format.html { render :edit }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /destinations/1
  # DELETE /destinations/1.json
  def destroy
    @destination.destroy
    respond_to do |format|
      format.html { redirect_to destinations_url, notice: 'Destination was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_destination
      @destination = Destination.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def destination_params
      params.require(:destination).permit(:name, :destination_type_id, :address, :city, :state, :zip, :price, :hours, :phone, :website, :facebook, :heading, :subheading, :gpscoords)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destination_types_helper.rb
module DestinationTypesHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/destination_types/_form.html.erb
<%= form_for(@destination_type) do |f| %>
  <% if @destination_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@destination_type.errors.count, "error") %> prohibited this destination_type from being saved:</h2>

      <ul>
      <% @destination_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/destination_types/edit.html.erb
<h1>Editing Destination Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @destination_type %> |
<%= link_to 'Back', destination_types_path %>

app/views/destination_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Destination Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @destination_types.each do |destination_type| %>
      <tr>
        <td><%= destination_type.name %></td>
        <td><%= link_to 'Show', destination_type %></td>
        <td><%= link_to 'Edit', edit_destination_type_path(destination_type) %></td>
        <td><%= link_to 'Destroy', destination_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Destination type', new_destination_type_path %>

app/views/destination_types/new.html.erb
<h1>New Destination Type</h1>

<%= render 'form' %>

<%= link_to 'Back', destination_types_path %>

app/views/destination_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @destination_type.name %>
</p>

<%= link_to 'Edit', edit_destination_type_path(@destination_type) %> |
<%= link_to 'Back', destination_types_path %>

app/views/destinations/_form.html.erb
<%= form_for(@destination) do |f| %>
  <% if @destination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@destination.errors.count, "error") %> prohibited this destination from being saved:</h2>

      <ul>
      <% @destination.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :destination_type_id %><br>
    <%= f.select :destination_type, @destination_types %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :hours %><br>
    <%= f.text_field :hours %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :facebook %><br>
    <%= f.text_field :facebook %>
  </div>
  <div class="field">
    <%= f.label :heading %><br>
    <%= f.text_field :heading %>
  </div>
  <div class="field">
    <%= f.label :subheading %><br>
    <%= f.text_field :subheading %>
  </div>
  <div class="field">
    <%= f.label :gpscoords %><br>
    <%= f.text_field :gpscoords %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/destinations/edit.html.erb
<h1>Editing Destination</h1>

<%= render 'form' %>

<%= link_to 'Show', @destination %> |
<%= link_to 'Back', destinations_path %>

app/views/destinations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Destinations</h1>


<div class="ui inline dropdown">
  <input type="hidden" name="gender">
  <div class="text">Shiba Inu</div>
  <i class="dropdown icon"></i>
  <div class="menu">
    <div class="item">
      <i class="dropdown icon"></i>
      <span class="text">Dogs</span>
      <div class="menu">
        <div class="item">Shiba Inu</div>
        <div class="item">Poodle</div>
        <div class="item">Labrador</div>
      </div>
    </div>
    <div class="item">
      <i class="dropdown icon"></i>
      <span class="text">Cats</span>
      <div class="menu">
        <div class="item">Aegean</div>
        <div class="item">Balinese</div>
        <div class="item">Persian</div>
      </div>
    </div>
  </div>
</div>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Destination type</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Price</th>
      <th>Hours</th>
      <th>Phone</th>
      <th>Website</th>
      <th>Facebook</th>
      <th>Heading</th>
      <th>Subheading</th>
      <th>Gpscoords</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @destinations.each do |destination| %>
      <tr>
        <td><%= destination.name %></td>
        <td><%= destination.destination_type %></td>
        <td><%= destination.address %></td>
        <td><%= destination.city %></td>
        <td><%= destination.state %></td>
        <td><%= destination.zip %></td>
        <td><%= destination.price %></td>
        <td><%= destination.hours %></td>
        <td><%= destination.phone %></td>
        <td><%= link_to 'WWW', destination.website %></td>
        <td><%= link_to 'FB', destination.facebook %></td>
        <td><%= destination.heading %></td>
        <td><%= destination.subheading %></td>
        <td><%= destination.gpscoords %></td>
        <td><%= link_to 'Show', destination %></td>
        <td><%= link_to 'Edit', edit_destination_path(destination) %></td>
        <td><%= link_to 'Destroy', destination, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Destination', new_destination_path %>

app/views/destinations/new.html.erb
<h1>New Destination</h1>

<%= render 'form' %>

<%= link_to 'Back', destinations_path %>

app/views/destinations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @destination.name %>
</p>

<p>
  <strong>Destination type:</strong>
  <%= @destination.destination_type %>
</p>

<p>
  <strong>Address:</strong>
  <%= @destination.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @destination.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @destination.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @destination.zip %>
</p>

<p>
  <strong>Price:</strong>
  <%= @destination.price %>
</p>

<p>
  <strong>Hours:</strong>
  <%= @destination.hours %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @destination.phone %>
</p>

<p>
  <strong>Website:</strong>
  <%= @destination.website %>
</p>

<p>
  <strong>Facebook:</strong>
  <%= @destination.facebook %>
</p>

<p>
  <strong>Heading:</strong>
  <%= @destination.heading %>
</p>

<p>
  <strong>Subheading:</strong>
  <%= @destination.subheading %>
</p>

<p>
  <strong>Gpscoords:</strong>
  <%= @destination.gpscoords %>
</p>

<%= link_to 'Edit', edit_destination_path(@destination) %> |
<%= link_to 'Back', destinations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dabble</title>
  <h1>Dabble Date</h1>
  <img src="/assets/dabble.jpg">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.password %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>